### ISSUE TITLE
Fails with additional parameters

### ISSUE THREAD

**Issue by mfisher911** [kidd/erc-youtube.el#2]
[This URL](https://www.youtube.com/watch?v=I0kWZP9L9Kc&list=PL2VAYZE_4wRKKr5pJzfYD1w4tKCXARs5y&index=2) was not properly resolved.

This also addresses URLs with dashes in them, such as [example 2](https://www.youtube.com/watch?v=GLJbQ-mMusI).

piyo@freenode recommended this patch to resolve it:

```
--- a/erc-youtube.el
+++ b/erc-youtube.el
@@ -78,7 +78,8 @@
            (put-text-property pt-before (point) 'read-only t)))))))

 (defun erc-youtube-id (url)
-       (replace-regexp-in-string ".*youtube.com/watch\\?v=\\([a-zA-Z0-9]+\\)" "\\1" url))
+  (replace-regexp-in-string
+   ".*youtube.com/watch\\?v=\\([-a-zA-Z0-9]+\\)\\(&.*\\)?" "\\1" url))

 (defun erc-youtube-show-info ()
   (interactive)
```

I'm happy to resubmit it as a pull request.

**Comment by piyo** [comment]
Another satisfied user!
